-- USE DATABASE ALREADY CREATED IN SETUP
USE nutrition_clinic;
GO

-- AUDIT LOG TABLE
CREATE TABLE AuditLog (
    auditID INT IDENTITY(1,1) PRIMARY KEY,
    tableName NVARCHAR(100) NOT NULL,
    recordID INT NOT NULL,
    action NVARCHAR(10) NOT NULL, -- INSERT / UPDATE / DELETE
    changedBy NVARCHAR(100) NULL,
    changeDate DATETIME NOT NULL DEFAULT GETDATE(),
    oldData NVARCHAR(MAX) NULL,
    newData NVARCHAR(MAX) NULL
);
